### ISSUE TITLE
TODO: изучить пакеты

### ISSUE THREAD

**Issue by pacahon** [cscenter/lms#134]
Наверняка что-то есть полезное:
- [x] http://django-secure.readthedocs.org/en/v0.1.2/
- [x] https://github.com/ui/django-rq Redis queue
- [x] https://github.com/ui/rq-scheduler
- [x] https://github.com/teddziuba/django-sslserver
- [x] https://github.com/asaglimbeni/django-datetime-widget
- [x] https://github.com/alex/django-filter/tree/master <- mb useful on student search page
- [x] https://github.com/niwinz/django-jinja <- for future redesign
- [x] https://github.com/tricoder42/django-sites-toolbar
