### ISSUE TITLE
Небольшой редизайн к большим анонсам

### ISSUE THREAD

**Issue by katyasosa** [cscenter/lms#153]
- [x] Страница про онлайн-курсы #145
- [x] Раздел Видео в верхнем меню заменить на Онлайн #146
- [x] Поменять лого ШАД #150
- [x] Поменять подвал #148 и заменить там цвет, в частности, #147
- [x] Убрать жирный шрифт #152
- [x] Изменить высоту меню #151
- [x] Заменить лого в меню (пока нет)
- [x] Убрать раздел новости #149 (пока не факт)
