### ISSUE TITLE
TODO: frontend, 9 circles of hell

### ISSUE THREAD

**Issue by pacahon** [cscenter/lms#370]
За 1 раз не потяну весь зоопарк, пожалуй, надо постепенно привыкать. 
Накидаю порядок, потом вернусь:

- [x] https://www.caktusgroup.com/blog/2016/05/02/es6-django-lovers/
- [ ]  Перевести gruntfile.js на webpack для освоения webpack. Есть подозрение, что grunt мне не нужен в принципе, если всё равно вводить webpack в игру. Отправная точка -  `sass-loader`
- [x] Изучить +- пакета `django-webpack-loader`. Так ли он упростит взаимодействие.
- [x] Понять, нужен ли мне `webpack-stats`
- [ ] hot-reloading для react http://owaislone.org/blog/webpack-plus-reactjs-and-django/
- [ ] Собственно, освоить react/jsx/babel, ради чего всё и затевается. Убедиться, что всё работает.
- [ ] Свыкнуться с мыслью, что современное js-приложение тянет зависимостей на пару мегабайт.
- [x] Настроить dev/prod окружения
- [ ] redux?

Nice tutorial:

http://geezhawk.github.io/using-react-with-django-rest-framework

Related links:

https://github.com/Seedstars/django-react-redux-base
https://github.com/bigsassy/drf-react-redux
